apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prepare-container
subjects:
- kind: ServiceAccount
  name: prepare-container
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: prepare-container
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prepare-container
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prepare-container