FROM ubuntu:mantic
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
    apt install -y --no-install-recommends libguestfs-tools rsync parallel && \
    apt clean -y
ENV LIBGUESTFS_BACKEND direct
ENV LIBGUESTFS_BACKEND_SETTINGS force_tcg
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
    apt install -y --no-install-recommends yq && \
    apt clean -y
