{{- if and .Values.validatingWebhook.enabled .Values.validatingWebhook.rbac.enabled }}
# RBAC file for the snapshot webhook.
#
# The snapshot webhook implements the validation and admission for CSI snapshot functionality.
# It should be installed as part of the base Kubernetes distribution in an appropriate
# namespace for components implementing base system functionality. For installing with
# Vanilla Kubernetes, kube-system makes sense for the namespace.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "snapshot-controller.name" . }}
    helm.sh/chart: {{ include "snapshot-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-webhook-runner
  labels:
    app.kubernetes.io/name: {{ include "snapshot-controller.name" . }}
    helm.sh/chart: {{ include "snapshot-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-webhook-role
  labels:
    app.kubernetes.io/name: {{ include "snapshot-controller.name" . }}
    helm.sh/chart: {{ include "snapshot-controller.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: snapshot-webhook
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: snapshot-webhook-runner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
