apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-files-{{ .Values.vm.name }}
spec:
  storageClassName: {{ .Values.pvc.storageClass | required ".Values.pvc.storageClass is required!" }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}