vm:
  name: vm
  config: vm.xml
  disk: vm.img
  diskFormat: img
job:
  image: daocloud.io/daocloud/libguestfs-tools
pvc:
  size: 10Gi
  storageClass:
  accessMode: ReadWriteOnce
  volumeMode: Filesystem

extractMethod: libguestfs # or 7zip
libguestfs:
  kvm:
    enabled: false
7zip:
