apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-{{ .Values.vm.name }}-restored-from-snapshot-0
spec:
  storageClassName: {{ .Values.pvc.storageClass | required ".Values.pvc.storageClass is required!" }}
  accessModes:
  - {{ .Values.pvc.accessMode }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: root-{{ .Values.vm.name }}-snapshot-0