apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: root-{{ .Values.vm.name }}-snapshot-0
spec:
  volumeSnapshotClassName: iscsi-zfs
  source:
    persistentVolumeClaimName: root-{{ .Values.vm.name }}-0