apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  labels:
    app.kubernetes.io/instance: hostpath.csi.k8s.io
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ .Values.storageClass.server }}
  share: /
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1