apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lamp
spec:
  selector:
    matchLabels:
      app: lamp
  serviceName: lamp
  replicas: 1
  template:
    metadata:
      labels:
        app: lamp
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: k8s-worker-1
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      # hostname: lamp
      containers:
      - name: lamp
        image: daocloud.io/daocloud/binless
        imagePullPolicy: Always
        command:
          - /sbin/init
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        readinessProbe:
          # tcpSocket:
          #   port: ssh # default as ssh; for apps, use app port such as http's 80
          exec: # for empty os, just check if journald is up
            command:
            - systemctl
            - is-active
            - systemd-journald
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: run
          mountPath: /run
        - name: root
          mountPath: /Users
          subPath: Users
        - name: root
          mountPath: /bin
          subPath: bin
        - name: root
          mountPath: /etc
          subPath: etc
        - name: root
          mountPath: /home
          subPath: home
        - name: root
          mountPath: /lib
          subPath: lib
        - name: root
          mountPath: /lib64
          subPath: lib64
        - name: root
          mountPath: /lost+found
          subPath: lost+found
        - name: root
          mountPath: /media
          subPath: media
        - name: root
          mountPath: /mnt
          subPath: mnt
        - name: root
          mountPath: /opt
          subPath: opt
        - name: root
          mountPath: /root
          subPath: root
        - name: root
          mountPath: /sbin
          subPath: sbin
        - name: root
          mountPath: /srv
          subPath: srv
        - name: root
          mountPath: /usr
          subPath: usr
        - name: root
          mountPath: /var
          subPath: var
        - name: root
          mountPath: /tmp
          subPath: tmp
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: run
        emptyDir:
          medium: Memory
      - name: root
        persistentVolumeClaim:
          claimName: root-lamp-0
---
apiVersion: v1
kind: Service
metadata:
  name: lamp
  labels:
    app: lamp
spec:
  type: NodePort
  selector:
    app: lamp
  ports:
  - port: 22
    name: ssh
  - port: 80
    name: http