customLabels: {}
image:
    nfs:
        repository: k8s.m.daocloud.io/sig-storage/nfsplugin
        tag: v4.4.0
        pullPolicy: IfNotPresent
    csiProvisioner:
        repository: k8s.m.daocloud.io/sig-storage/csi-provisioner
        tag: v3.5.0
        pullPolicy: IfNotPresent
    csiSnapshotter:
        repository: k8s.m.daocloud.io/sig-storage/csi-snapshotter
        tag: v6.2.2
        pullPolicy: IfNotPresent
    livenessProbe:
        repository: k8s.m.daocloud.io/sig-storage/livenessprobe
        tag: v2.10.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: k8s.m.daocloud.io/sig-storage/csi-node-driver-registrar
        tag: v2.8.0
        pullPolicy: IfNotPresent
    externalSnapshotter:
        repository: k8s.m.daocloud.io/sig-storage/snapshot-controller
        tag: v6.2.2
        pullPolicy: IfNotPresent

serviceAccount:
  create: true # When true, service accounts will be created for you. Set to false if you want to use your own.
  controller: csi-nfs-controller-sa # Name of Service Account to be created or used

rbac:
  create: true
  name: nfs

driver:
  name: nfs.csi.k8s.io
  mountPermissions: 0

feature:
  enableFSGroupPolicy: true
  enableInlineVolume: true

kubeletDir: /var/lib/kubelet

controller:
  name: csi-nfs-controller
  replicas: 1
  strategyType: Recreate
  runOnMaster: false
  runOnControlPlane: false
  livenessProbe:
    healthPort: 29652
  logLevel: 5
  workingMountDir: /tmp
  dnsPolicy: ClusterFirstWithHostNet  # available values: Default, ClusterFirstWithHostNet, ClusterFirst
  defaultOnDeletePolicy: delete  # available values: delete, retain
  affinity: {}
  nodeSelector: {}
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  resources:
    csiProvisioner: {}
    csiSnapshotter: {}
    livenessProbe: {}
    nfs: {}

node:
  name: csi-nfs-node
  dnsPolicy: ClusterFirstWithHostNet  # available values: Default, ClusterFirstWithHostNet, ClusterFirst
  maxUnavailable: 1
  logLevel: 5
  livenessProbe:
    healthPort: 29653
  affinity: {}
  nodeSelector: {}
  tolerations:
    - operator: "Exists"
  resources:
    livenessProbe: {}
    nodeDriverRegistrar: {}
    nfs: {}

externalSnapshotter:
  enabled: true
  name: snapshot-controller
  controller:
    replicas: 1
  resources: {}
## Reference to one or more secrets to be used when pulling images
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
# - name: "image-pull-secret"

storageClass:
  server: server.nfs.io
