apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: start-container
subjects:
- kind: ServiceAccount
  name: start-container
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: start-container
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: start-container
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: start-container