apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-{{ .Values.vm.name }}-0
spec:
  storageClassName: {{ .Values.pvc.storageClass | required ".Values.pvc.storageClass is required!" }}
  accessModes:
  - {{ .Values.pvc.accessMode }}
  volumeMode: {{ .Values.pvc.volumeMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}